### ISSUE TITLE
Buffer Out of Bounds

### ISSUE THREAD

**Issue by dmckillican** [rainlake/node-lightify#6]
An error occurs when the number of lighting lamps exceeds 29. Homebridge will no longer run, with an "out of bounds" error related to the index.js code.

The error is as below, and was resolved by reducing the number of lamps to 28.

This node is exceptional and has solved a lot of problems for me, namely, having invested $2,000 in lamps only to find out that Apple has revoked the HomeKit approval. If this is something you are able to resolve I would be most grateful.

buffer.js:829
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:829:11)
    at Uint8Array.Buffer.readUInt16LE (buffer.js:875:5)
    at /usr/local/lib/node_modules/homebridge-lightify/node_modules/node-lightify/index.js:116:22
    at responseProcesser (/usr/local/lib/node_modules/homebridge-lightify/node_modules/node-lightify/index.js:81:18)
    at Object.processer (/usr/local/lib/node_modules/homebridge-lightify/node_modules/node-lightify/index.js:109:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-lightify/node_modules/node-lightify/index.js:47:54)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)

**Comment by rainlake** [comment]
this issue is fixed for v2, you might want use this version in your app. thanks!
